const bankOptions = [
    "BANCO CENTRAL DEL ECUADOR",
    "BANCO NACIONAL DE FOMENTO",
    "BANCO AMAZONAS",
    "BANCO DEL PACIFICO",
    "BANCO PICHINCHA",
    "BANCO DE MACHALA",
    "BANCO SUDAMERICANO",
    "PRODUBANCO",
    "BANCO INTERNACIONAL",
    "COOPERATIVA DE AHORRO Y CRÉDITO CÁMARA DE COMERCIO AMBATO",
    "BANCO PROMERICA",
    "COOPERATIVA DE AHORRO Y CRÉDITO 'EL DISCAPACITADO' LTDA.",
    "BANCO CAPITAL S.A.",
    "FINANCIERA DE LA REPUBLICA S.A 'FIRESA'"
  ];
  
  export default bankOptions;
  